package cronparser

import (
	"encoding/json"
	"math"
	"os"
	"testing"
)

// TestPRNGMatchesUpstream verifies the xfnv1a + mulberry32 transcription against
// vectors generated by the original TypeScript implementation.
//
// Vectors produced by upstream/_probe/prng.mjs. The "😀" case exercises the
// UTF-16 surrogate-pair path, where Go's rune iteration would diverge from JS's
// charCodeAt if not handled.
func TestPRNGMatchesUpstream(t *testing.T) {
	raw, err := os.ReadFile("testdata_prng.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}

	var want map[string][]float64
	if err := json.Unmarshal(raw, &want); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	if len(want) == 0 {
		t.Fatal("no vectors loaded")
	}

	for seed, expected := range want {
		rand := seededRandom(seed)
		for i, exp := range expected {
			got := rand()
			// These must agree bit-for-bit: both sides compute
			// uint32 / 2^32, which is exactly representable in float64.
			if got != exp {
				t.Errorf("seed %q call %d: got %.17g want %.17g (delta %g)",
					seed, i, got, exp, math.Abs(got-exp))
			}
		}
	}
}

func TestToUint32(t *testing.T) {
	cases := []struct {
		in   float64
		want uint32
	}{
		{0, 0},
		{1, 1},
		{4294967295, 4294967295},
		{4294967296, 0},          // 2^32 wraps
		{4294967297, 1},          // 2^32+1
		{-1, 4294967295},         // negative wraps
		{1.9, 1},                 // truncates toward zero
		{-1.9, 4294967295},       // trunc(-1.9) = -1 -> wraps
		{8589934592, 0},          // 2^33
		{math.NaN(), 0},          // ToUint32(NaN) = 0
		{math.Inf(1), 0},         // ToUint32(Inf) = 0
	}
	for _, c := range cases {
		if got := toUint32(c.in); got != c.want {
			t.Errorf("toUint32(%v) = %d, want %d", c.in, got, c.want)
		}
	}
}

func TestUTF16Units(t *testing.T) {
	// "😀" is U+1F600, which JS stores as the surrogate pair D83D DE00.
	got := utf16Units("😀")
	if len(got) != 2 || got[0] != 0xD83D || got[1] != 0xDE00 {
		t.Errorf("utf16Units(😀) = %#v, want [D83D DE00]", got)
	}
	// BMP characters map 1:1.
	if got := utf16Units("é"); len(got) != 1 || got[0] != 0xE9 {
		t.Errorf("utf16Units(é) = %#v, want [00E9]", got)
	}
}
